# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  - name: sourceFolder
    value: "src"

jobs:
  - job: build
    displayName: "Build Job"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"
        displayName: "Install Node.js"

      - script: |
          yarn install
        displayName: "yarn install"
        workingDirectory: $(sourceFolder)

      - script: |
          yarn run build
        displayName: "npm build"
        workingDirectory: $(sourceFolder)

      - script: |
          yarn run test
        displayName: "npm test:ci"
        workingDirectory: $(sourceFolder)

      - task: PublishTestResults@2
        displayName: 'supply npm test results to pipelines'
        condition: succeededOrFailed() # because otherwise we won't know what tests failed
        inputs:
          testResultsFiles: 'src/reports/junit.xml'