# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest
variables:
  - name: sourceFolder
    value: "src"

jobs:
  - job: build
    displayName: "Build Job"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"
        displayName: "Install Node.js"

      - script: |
          yarn install
        displayName: "Install dependencies"
        workingDirectory: $(sourceFolder)

      - script: |
          yarn run build
        displayName: "Build application"
        workingDirectory: $(sourceFolder)

      - script: |
          yarn run test:ci
        displayName: "Run tests"
        workingDirectory: $(sourceFolder)

      - task: PublishTestResults@2
        displayName: "Publish test results"
        condition: succeededOrFailed() # because otherwise we won't know what tests failed
        inputs:
          testResultsFiles: "src/reports/junit.xml"

      - task: PublishCodeCoverageResults@2
        displayName: "Publish code coverage"
        inputs:
          summaryFileLocation: "src/coverage/cobertura-coverage.xml"
          reportDirectory: "src/coverage"
